apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "shipping.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "shipping.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "shipping.labels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      name: {{ template "shipping.fullname" . }}
      namespace: {{ .Release.Namespace }}
      labels: {{ include "shipping.labels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ template "shipping.fullname" . }}
        image: {{ .Values.shipping.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.shipping.port | int }}
        env: 
          - name: WEBSHOP_PORT
            value: {{ .Values.shipping.port | quote }}
{{ include "webshop.db.env.secrets.shipping" . | indent 10 }} 
{{ include "webshop.db.env.connection" . | indent 10 }}
