apiVersion: v1
kind: Service
metadata:
  name: {{ template "shipping.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.shipping.service.port }}
    targetPort: {{ .Values.shipping.port }}
    protocol: TCP
  selector: {{ include "shipping.labels" . | nindent 4 }}
