apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "cart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "cart.labels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      name: {{ template "cart.fullname" . }}
      namespace: {{ .Release.Namespace }}
      labels: {{ include "cart.labels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ template "cart.fullname" . }}
        image: {{ .Values.cart.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.cart.port | int }}
        env: 
          - name: WEBSHOP_PORT
            value: {{ .Values.cart.port | quote }}
{{ include "webshop.db.env.secrets.cart" . | indent 10 }} 
{{ include "webshop.db.env.connection" . | indent 10 }}
