apiVersion: v1
kind: Service
metadata:
  name: {{ template "cart.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.cart.service.port }}
    targetPort: {{ .Values.cart.port }}
    protocol: TCP
  selector: {{ include "cart.labels" . | nindent 4 }}
