apiVersion: v1
kind: Service
metadata:
  name: {{ template "postgres.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: {{ .Values.postgres.service.port }}
    targetPort: {{ .Values.postgres.port }}
    protocol: TCP
  selector: {{ include "postgres.labels" . | nindent 4 }}
