apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    name: kafka
spec:
  selector:
    app: kafka
    id: "0"
  ports:
  - port: 9092
    nodePort: 31041
    name: kafka-port
    protocol: TCP
  type: NodePort