apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
spec:
  selector:
    matchLabels:
      app: catalog-service
  replicas: 1
  template: # template for the pod
      metadata:
        labels:
          app: catalog-service
      spec:
        containers:
          - name: catalog-service
            image: trnhan251/catalog-service:latest

