apiVersion: v1
kind: Secret
metadata:
  name: {{ template "webshop.fullname" . }}-auth-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  catalogUsername: {{ .Values.catalog.auth.username | b64enc }}
  catalogPassword: {{ default (randAlphaNum (.Values.genPasswordLength | int)) .Values.catalog.auth.password | b64enc }}

  cartUsername: {{ .Values.cart.auth.username | b64enc }}
  cartPassword: {{ default (randAlphaNum (.Values.genPasswordLength | int)) .Values.cart.auth.password | b64enc }}

  shippingUsername: {{ .Values.shipping.auth.username | b64enc }}
  shippingPassword: {{ default (randAlphaNum (.Values.genPasswordLength | int)) .Values.shipping.auth.password | b64enc }}

  checkoutUsername: {{ .Values.checkout.auth.username | b64enc }}
  checkoutPassword: {{ default (randAlphaNum (.Values.genPasswordLength | int)) .Values.checkout.auth.password | b64enc }}
