kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "checkout.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  applicationYml: |
    server:
      port: {{ .Values.checkout.port }}

    spring:
      application.name: checkout
      main:
        web-application-type: reactive
        cloud-platform: kubernetes
      profiles.active: production

    management:
      server.port: {{ .Values.checkout.managementPort | int }}
      endpoint:
        metrics:
          enabled: true
        prometheus.enabled: true
        health.show-details: always
      metrics.export.prometheus.enabled: true
      endpoints.web.exposure.include: "*"
      health:
        circuitbreakers.enabled: true
        ratelimiters.enabled: true
        diskspace.enabled: false
      security.enabled: false

    logging.level.root: {{ .Values.checkout.loglevel }}

    resilience4j:
      circuitbreaker:
        configs:
          default:
            registerHealthIndicator: true
            minimumNumberOfCalls: 10
            waitDurationInOpenState: 20s
            failureRateThreshold: 50
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            slidingWindowSize: 100
            recordExceptions:
              - org.springframework.web.client.HttpServerErrorException
              - java.util.concurrent.TimeoutException
              - java.io.IOException
        instances:
          checkout:
            baseConfig: default
{{ include "checkout.r4j.circuitbreaker.checkout" . | indent 12 }}

      retry:
        configs:
          default:
            maxRetryAttempts: 3
            waitDuration: 1500
            enableExponentialBackoff: true
            exponentialBackoffMultiplier: 2.2
            retryExceptions:
              - org.springframework.web.client.HttpServerErrorException
              - java.io.IOException
        instances:
          checkout:
            baseConfig: default
{{ include "checkout.r4j.retry.checkout" . | indent 12 }}

      thread-pool-bulkhead:
        configs:
          default:
            maxThreadPoolSize: 4
            coreThreadPoolSize: 1
            queueCapacity: 10
            keepAliveDuration: 200
        instances:
          checkout:
            baseConfig: default
{{ include "checkout.r4j.thread_pool_bulkhead.checkout" . | indent 12 }}

      ratelimiter:
        configs:
          default:
            registerHealthIndicator: true
            limitForPeriod: 10
            limitRefreshPeriod: 1s
            timeoutDuration: 0
        instances:
          checkout:
            baseConfig: default
{{ include "checkout.r4j.ratelimiter.checkout" . | indent 12 }}

      timelimiter:
        configs:
          default:
            timeoutDuration: 5s
            cancelRunningFuture: true
        instances:
          checkout:
            baseConfig: default
{{ include "checkout.r4j.timelimiter.checkout" . | indent 12 }}
