apiVersion: v1
kind: Service
metadata:
  name: {{ template "checkout.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.checkout.service.port }}
    targetPort: {{ .Values.checkout.port }}
    protocol: TCP
  selector: {{ include "checkout.labels" . | nindent 4 }}
