apiVersion: v1
kind: Service
metadata:
  name: {{ template "frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.port }}
    protocol: TCP
  selector: {{ include "frontend.labels" . | nindent 4 }}
