kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "postgres.fullname" . }}-init-config
  namespace: {{ .Release.Namespace }}
data:
  init: |
    #!/bin/bash

    PGPASSWORD=$POSTGRES_PASSWORD

    cmd="
    DROP SCHEMA public;

    CREATE SCHEMA $WEBSHOP_CATALOG_DB_SCHEMA;
    CREATE SCHEMA $WEBSHOP_CART_DB_SCHEMA;
    CREATE SCHEMA $WEBSHOP_SHIPPING_DB_SCHEMA;

    CREATE USER $WEBSHOP_CATALOG_DB_USERNAME WITH PASSWORD '$WEBSHOP_CATALOG_DB_PASSWORD';
    GRANT ALL ON SCHEMA $WEBSHOP_CATALOG_DB_SCHEMA TO $WEBSHOP_CATALOG_DB_USERNAME;

    CREATE USER $WEBSHOP_CART_DB_USERNAME WITH PASSWORD '$WEBSHOP_CART_DB_PASSWORD';
    GRANT ALL ON SCHEMA $WEBSHOP_CART_DB_SCHEMA TO $WEBSHOP_CART_DB_USERNAME;

    CREATE USER $WEBSHOP_SHIPPING_DB_USERNAME WITH PASSWORD '$WEBSHOP_SHIPPING_DB_PASSWORD';
    GRANT ALL ON SCHEMA $WEBSHOP_SHIPPING_DB_SCHEMA TO $WEBSHOP_SHIPPING_DB_USERNAME;
    "

    psql -U$POSTGRES_USER -d$POSTGRES_DB -c "$cmd"
