kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "postgres.fullname" . }}-init-config
  namespace: {{ .Release.Namespace }}
data:
  init: |
    #!/bin/bash

    PGPASSWORD=$POSTGRES_PASSWORD

    cmd="
    DROP SCHEMA public;

    CREATE SCHEMA $WEBSHOP_CATALOG_SCHEMA;
    CREATE SCHEMA $WEBSHOP_CART_SCHEMA;
    CREATE SCHEMA $WEBSHOP_SHIPPING_SCHEMA;

    CREATE USER $WEBSHOP_CATALOG_USER WITH ENCRYPTED PASSWORD '$WEBSHOP_CATALOG_USER_PASSWORD';
    GRANT ALL ON SCHEMA $WEBSHOP_CATALOG_SCHEMA TO $WEBSHOP_CATALOG_USER;

    CREATE USER $WEBSHOP_CART_USER WITH ENCRYPTED PASSWORD '$WEBSHOP_CART_USER_PASSWORD';
    GRANT ALL ON SCHEMA WEBSHOP_CART_SCHEMA TO $WEBSHOP_CART_USER;

    CREATE USER $WEBSHOP_SHIPPING_USER WITH ENCRYPTED PASSWORD '$WEBSHOP_SHIPPING_USER_PASSWORD';
    GRANT ALL ON SCHEMA $WEBSHOP_SHIPPING_SCHEMA TO $WEBSHOP_SHIPPING_USER;
    "

    psql -U$POSTGRES_USER -c "$cmd"
