apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "postgres.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels: {{ include "postgres.labels" . | nindent 6 }}
  serviceName: {{ template "postgres.fullname" . }}-headless
  replicas: 1
  template:
    metadata:
      labels: {{ include "postgres.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ template "postgres.fullname" . }}
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: {{ .Values.postgres.port }}
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "webshop.fullname" . }}-db-secrets
                  key: postgresPassword
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ template "webshop.fullname" . }}-db-secrets
                  key: postgresUsername
            - name: POSTGRES_DB
              value: {{ default .Values.postgres.db ("" | quote) }}
            - name: PGDATA
              value: {{ .Values.postgres.dataDir }}
            - name: WEBSHOP_CATALOG_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: {{ template "webshop.fullname" . }}-db-secrets
                  key: catalogSchema
            - name: WEBSHOP_CATALOG_USER
              valueFrom:
                secretKeyRef:
                  name: {{ template "webshop.fullname" . }}-db-secrets
                  key: catalogUsername
            - name: WEBSHOP_CATALOG_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "webshop.fullname" . }}-db-secrets
                  key: catalogPassword
            - name: WEBSHOP_CART_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: {{ template "webshop.fullname" . }}-db-secrets
                  key: cartSchema
            - name: WEBSHOP_CART_USER
              valueFrom:
                secretKeyRef:
                  name: {{ template "webshop.fullname" . }}-db-secrets
                  key: cartUsername
            - name: WEBSHOP_CART_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "webshop.fullname" . }}-db-secrets
                  key: cartPassword
            - name: WEBSHOP_SHIPPING_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: {{ template "webshop.fullname" . }}-db-secrets
                  key: shippingSchema
            - name: WEBSHOP_SHIPPING_USER
              valueFrom:
                secretKeyRef:
                  name: {{ template "webshop.fullname" . }}-db-secrets
                  key: shippingUsername
            - name: WEBSHOP_SHIPPING_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "webshop.fullname" . }}-db-secrets
                  key: shippingPassword
          volumeMounts:
            - name: {{ template "postgres.fullname" . }}-datav
              mountPath: {{ .Values.postgres.dataDir }}
            - name: {{ template "postgres.fullname" . }}-initv
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: {{ template "postgres.fullname" . }}-initv
          configMap:
            name: {{ template "postgres.fullname" . }}-init-config
            items:
              - key: init
                path: init.sh
  volumeClaimTemplates:
    - metadata:
        name: {{ template "postgres.fullname" . }}-datav
        namespace: {{ .Release.Namespace }}
      spec:
        storageClassName: {{ template "webshop.fullname" . }}-sc
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: {{ .Values.postgres.storageSize }}
