apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "catalog.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "catalog.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "catalog.labels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: {{ .Values.catalog.managementPort | quote }}
      name: {{ template "catalog.fullname" . }}
      namespace: {{ .Release.Namespace }}
      labels: {{ include "catalog.labels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ template "catalog.fullname" . }}
        image: {{ .Values.catalog.image }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: {{ .Values.catalog.managementPort | int }}
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: {{ .Values.catalog.managementPort | int }}
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
        - containerPort: {{ .Values.catalog.port | int }}
        volumeMounts:
        - name: {{ template "catalog.fullname" . }}-application-yml
          mountPath: /app/config
        env: 
{{ include "webshop.db.env.secrets.catalog" . | indent 10 }} 
{{ include "webshop.db.env.connection" . | indent 10 }}
{{ include "webshop.auth.env.catalog" . | indent 10 }}
{{ include "webshop.env.host" . | indent 10 }}
      volumes:
        - name: {{ template "catalog.fullname" . }}-application-yml
          configMap:
            name: {{ template "catalog.fullname" . }}-config
            items:
            - key: applicationYml
              path: application.yml
