apiVersion: v1
kind: Service
metadata:
  name: {{ template "catalog.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.catalog.service.port }}
    targetPort: {{ .Values.catalog.port }}
    protocol: TCP
  selector: {{ include "catalog.labels" . | nindent 4 }}
