# Empty passwords will be randomly generated.

genPasswordLength: 12

namespace: webshop-demo

host: control-plane.minikube.internal

volume:
  storageSize: 5Gi
  path: /data/pv_webshop

postgres:
  service:
    port: 5432

  dataDir: /var/lib/postgresql/data
  database: ""
  storageSize: 1G

  username: postgres
  password: "postgres"
  db: "" # Database will be the same as .postgres.username if left empty.

  image: postgres:12.3-alpine
  port: 5432

catalog:
  image: yourjayer/catalog-service:latest
  port: 8080
  managementPort: 10080
  loglevel: INFO
  service:
    port: 8080
    managementPort: 10080
  db:
    schema: webshop_catalog_schema
    username: webshop_catalog_db_user
    password: "webshop_catalog_db_password"
  auth:
    username: webshop_catalog_auth_user
    password: "webshop_catalog_auth_password"
  resilience4j:
    retry:
      catalog:
    circuitbreaker:
      catalog:
    timelimiter:
      catalog:
    thread_pool_bulkhead:
      catalog:
    ratelimiter:
      catalog:

  
shipping:
  image: yourjayer/shipping-service:latest
  port: 8080
  managementPort: 10080
  loglevel: INFO
  service:
    port: 8080
    managementPort: 10080
  db:
    schema: webshop_shipping_schema
    username: webshop_shipping_db_user
    password: webshop_shipping_db_password
  auth:
    username: webshop_shipping_auth_user
    password: webshop_shipping_auth_password
  resilience4j:
    retry:
      shipping:
      cost:
    circuitbreaker:
      shipping:
      cost:
    timelimiter:
      shipping:
      cost:
    thread_pool_bulkhead:
      shipping:
      cost:
    ratelimiter:
      shipping:
      cost:

cart:
  image: yourjayer/cart-service:latest
  port: 8080
  managementPort: 10080
  loglevel: INFO
  service:
    port: 8080
    managementPort: 10080
  db:
    schema: webshop_cart_schema
    username: webshop_cart_db_user
    password: webshop_cart_db_password
  auth:
    username: webshop_cart_auth_user
    password: webshop_cart_auth_password
  resilience4j:
    retry:
      cart:
    circuitbreaker:
      cart:
    timelimiter:
      cart:
    thread_pool_bulkhead:
      cart:
    ratelimiter:
      cart:

checkout:
  image: yourjayer/checkout-service:latest
  port: 8080
  managementPort: 10080
  loglevel: INFO
  service:
    port: 8080
    managementPort: 10080
  auth:
    username: webshop_checkout_auth_user
    password: webshop_checkout_auth_password
  resilience4j:
    retry:
      checkout:
    circuitbreaker:
      checkout:
    timelimiter:
      checkout:
    thread_pool_bulkhead:
      checkout:
    ratelimiter:
      checkout:
